"
" vimrc
"
" vi互換モードをOFF(vimの拡張機能を有効)
set nocompatible

" ファイルタイプを判別しフィルタプラグインを有効化
filetype indent plugin on

" 色付けを有効
syntax on

" バックアップを作成しない
set nobackup

" バッファを保存しなくてもほかのバッファを表示できるようにする
set hidden

" コマンドライン補完を便利にする
set wildmenu

" 対応するかっこへ一瞬(0.1秒)飛ぶ
set showmatch
set matchtime=1

" 補完メニューの高さを調整
set pumheight=10

" タイプ途中のコマンドを画面最下行に表示
set showcmd

" <BS>の動作
set backspace=indent,eol,start

" 検索語を強調表示(Ctrl-Lを押すと現在の強調表示を解除する)
set hlsearch

" 検索時に大文字小文字を区別しない
" ただし、検索語に大文字小文字が混在しているときは区別する
set ignorecase
set smartcase

" オートインデント
set autoindent

" 移動コマンドを使ったとき、行頭に移動しない
set nostartofline

" 画面最下行にルーラーを表示する
set ruler

" ステータスラインを常に表示する
set laststatus=2

" バッファが変更されているとき、コマンドをエラーにするのではなく、保存するかどうか確認する
set confirm

" ビープ音の代わりにビジュアルベル(画面フラッシュ)を使用する
set visualbell

" ビジュアルベルも無効化する
set t_vb=

" 全モードでマウスを有効化
set mouse=a

" 長い行でもきちんと表示する
set display=lastline

" 行番号を表示
set number

" 行番号の左に空間を開ける
augroup numberwidth
  autocmd!
  autocmd BufEnter,WinEnter,BufWinEnter * let &l:numberwidth = len(line("$")) + 2
augroup END

" キーコードはすぐにタイムアウト。マッピングはタイムアウトしない
set notimeout ttimeout ttimeoutlen=200

" <F11>キーで'paste'と'nopaste'を切り替える
"set pastetoggle=<F11>

" インデント関連
" タブ文字の代わりにスペースを2個使う場合の設定
" この場合、'tabstop'はデフォルトの8から変更しない
set shiftwidth=2
set softtabstop=2
set expandtab

" インデントにハードタブを使う場合の設定
" タブ文字を2文字分の幅で表示する
" set shiftwidth=2
" set tabstop=2

" マッピング
" Yの動作をDやCと同じにする
map Y y$

" スワップファイルがあるときはリードオンリーにする
augroup swapchoice-readonly
  autocmd!
  autocmd SwapExists * let v:swapchoice='o'
augroup END

" Ctrl-Cで検索語の強調表示を加除する
nnoremap <C-L> :nohl<CR><C-L>

" 数字のインクリメント(+)デクリメント(-)
nnoremap + <C-a>
nnoremap + <C-x>
noremap!  

